"""empty message

Revision ID: 0f5c0510ac3f
Revises: 
Create Date: 2017-08-22 13:19:28.523629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5c0510ac3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BSConfig',
    sa.Column('bsid', sa.Integer(), nullable=False),
    sa.Column('bsip1', sa.String(length=64), nullable=True),
    sa.Column('bsip2', sa.String(length=64), nullable=True),
    sa.Column('ulPacketTime', sa.Integer(), nullable=True),
    sa.Column('ulPacketNum', sa.Integer(), nullable=True),
    sa.Column('dlLogicSubFrameNum', sa.Integer(), nullable=True),
    sa.Column('dlPacketTime', sa.Integer(), nullable=True),
    sa.Column('trxNum', sa.Integer(), nullable=True),
    sa.Column('bsPort1', sa.Integer(), nullable=True),
    sa.Column('bsPort2', sa.Integer(), nullable=True),
    sa.Column('ulCompetitionSectionTime', sa.Integer(), nullable=True),
    sa.Column('sin_family', sa.Integer(), nullable=True),
    sa.Column('dlLogicSubFrameIdx', sa.Integer(), nullable=True),
    sa.Column('Throughout', sa.Integer(), nullable=True),
    sa.Column('ulThroughout', sa.Integer(), nullable=True),
    sa.Column('dlThroughout', sa.Integer(), nullable=True),
    sa.Column('PacketMiss', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('bsid'),
    sa.UniqueConstraint('bsip1'),
    sa.UniqueConstraint('bsip2')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('TrxConfig',
    sa.Column('trxId', sa.Integer(), nullable=False),
    sa.Column('trxIp', sa.String(length=64), nullable=True),
    sa.Column('ssNum', sa.Integer(), nullable=True),
    sa.Column('trxPort', sa.Integer(), nullable=True),
    sa.Column('trxTxPower', sa.Integer(), nullable=True),
    sa.Column('trxDataRate', sa.Integer(), nullable=True),
    sa.Column('trxFreq', sa.Integer(), nullable=True),
    sa.Column('bs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bs_id'], [u'BSConfig.bsid'], ),
    sa.PrimaryKeyConstraint('trxId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrxConfig')
    op.drop_table('users')
    op.drop_table('BSConfig')
    # ### end Alembic commands ###
