"""empty message

Revision ID: 248d337dcb97
Revises: 7b195f24a57f
Create Date: 2017-09-27 09:28:08.992714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '248d337dcb97'
down_revision = '7b195f24a57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BSConfig', sa.Column('dlPacketTime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BSConfig', 'dlPacketTime')
    # ### end Alembic commands ###
