"""empty message

Revision ID: 5a93b8428441
Revises: 
Create Date: 2017-09-05 10:10:08.786215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a93b8428441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BSConfig',
    sa.Column('BSID', sa.Integer(), nullable=False),
    sa.Column('bs_name', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('BSIP1', sa.String(length=64), nullable=True),
    sa.Column('BSIP2', sa.String(length=64), nullable=True),
    sa.Column('BSPort1', sa.Integer(), nullable=True),
    sa.Column('BSPort2', sa.Integer(), nullable=True),
    sa.Column('BSGPS', sa.String(length=64), nullable=True),
    sa.Column('ulPacketTime', sa.Integer(), nullable=True),
    sa.Column('ulPacketNum', sa.Integer(), nullable=True),
    sa.Column('dlLogicSubFrameNum', sa.Integer(), nullable=True),
    sa.Column('dlPacketTime', sa.Integer(), nullable=True),
    sa.Column('ulCompetitionSectionTime', sa.Integer(), nullable=True),
    sa.Column('sin_family', sa.Integer(), nullable=True),
    sa.Column('dlLogicSubFrameIdx', sa.Integer(), nullable=True),
    sa.Column('Throughout', sa.Integer(), nullable=True),
    sa.Column('ulThroughout', sa.Integer(), nullable=True),
    sa.Column('dlThroughout', sa.Integer(), nullable=True),
    sa.Column('PacketMiss', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('BSID'),
    sa.UniqueConstraint('bs_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('TrxConfig',
    sa.Column('trx_name', sa.String(length=64), nullable=True),
    sa.Column('TRXID', sa.Integer(), nullable=False),
    sa.Column('TRXIP', sa.String(length=64), nullable=True),
    sa.Column('TRXPort', sa.Integer(), nullable=True),
    sa.Column('TRXTxPower', sa.Integer(), nullable=True),
    sa.Column('TRXDataRate', sa.Integer(), nullable=True),
    sa.Column('TRXFreq', sa.Integer(), nullable=True),
    sa.Column('BS_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['BS_ID'], [u'BSConfig.BSID'], ),
    sa.PrimaryKeyConstraint('TRXID')
    )
    op.create_table('SSConfig',
    sa.Column('ss_name', sa.String(length=64), nullable=True),
    sa.Column('SSID', sa.Integer(), nullable=False),
    sa.Column('SSIP', sa.String(length=64), nullable=True),
    sa.Column('SSGPS', sa.String(length=64), nullable=True),
    sa.Column('TRX_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TRX_ID'], [u'TrxConfig.TRXID'], ),
    sa.PrimaryKeyConstraint('SSID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SSConfig')
    op.drop_table('TrxConfig')
    op.drop_table('users')
    op.drop_table('BSConfig')
    # ### end Alembic commands ###
