"""empty message

Revision ID: 679d642d627f
Revises: 6575c538b160
Create Date: 2017-08-10 15:00:41.618963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '679d642d627f'
down_revision = '6575c538b160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BSConfig', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('BSConfig', 'active')
    # ### end Alembic commands ###
