"""empty message

Revision ID: 7b195f24a57f
Revises: 5a93b8428441
Create Date: 2017-09-27 09:27:28.108218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b195f24a57f'
down_revision = '5a93b8428441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BSConfig', 'dlPacketTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BSConfig', sa.Column('dlPacketTime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
